In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/hijest/genre-classification-dataset-imdb/Genre Classification Dataset/description.txt
/kaggle/input/datasets/hijest/genre-classification-dataset-imdb/Genre Classification Dataset/test_data_solution.txt
/kaggle/input/datasets/hijest/genre-classification-dataset-imdb/Genre Classification Dataset/test_data.txt
/kaggle/input/datasets/hijest/genre-classification-dataset-imdb/Genre Classification Dataset/train_data.txt

In [2]:
import os
os.listdir()

['.virtual_documents']

In [3]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [4]:
import os

for root, dirs, files in os.walk("/kaggle/input"):
    print(root)
    print(dirs)
    print(files)
    print("-" * 40)

/kaggle/input
['datasets']
[]
----------------------------------------
/kaggle/input/datasets
['hijest']
[]
----------------------------------------
/kaggle/input/datasets/hijest
['genre-classification-dataset-imdb']
[]
----------------------------------------
/kaggle/input/datasets/hijest/genre-classification-dataset-imdb
['Genre Classification Dataset']
[]
----------------------------------------
/kaggle/input/datasets/hijest/genre-classification-dataset-imdb/Genre Classification Dataset
[]
['description.txt', 'test_data_solution.txt', 'test_data.txt', 'train_data.txt']
----------------------------------------

In [5]:
import pandas as pd
import numpy as np
import re
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [6]:
def load_movie_data(file_path):
    data = []
    
    with open(file_path, "r", encoding="utf-8") as file:
        for line in file:
            parts = line.strip().split(" ::: ")
            if len(parts) == 4:
                data.append(parts)
    
    df = pd.DataFrame(
        data,
        columns=["id", "title", "genre", "plot"]
    )
    return df

In [7]:
train_path = "/kaggle/input/datasets/hijest/genre-classification-dataset-imdb/Genre Classification Dataset/train_data.txt"

data = load_movie_data(train_path)
data.head()

,id,title,genre,plot
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his doc...
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous re...
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fiel...
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends meet...
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-rec...

In [8]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text

In [9]:
data["plot"] = data["plot"].apply(clean_text)

In [10]:
X = data["plot"]
y = data["genre"]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [12]:
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [13]:
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [14]:
y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.5232869132158997

Classification Report:

              precision    recall  f1-score   support

      action       0.57      0.08      0.13       263
       adult       0.86      0.05      0.10       112
   adventure       0.47      0.06      0.10       139
   animation       0.00      0.00      0.00       104
   biography       0.00      0.00      0.00        61
      comedy       0.51      0.44      0.47      1443
       crime       0.00      0.00      0.00       107
 documentary       0.58      0.88      0.70      2659
       drama       0.46      0.83      0.59      2697
      family       1.00      0.01      0.01       150
     fantasy       0.00      0.00      0.00        74
   game-show       1.00      0.15      0.26        40
     history       0.00      0.00      0.00        45
      horror       0.72      0.37      0.49       431
       music       0.80      0.14      0.24       144
     musical       0.00      0.00      0.00        50
     mystery       0.00      0.00      0.00        56
        news       0.00      0.00      0.00        34
  reality-tv       0.80      0.02      0.04       192
     romance       0.00      0.00      0.00       151
      sci-fi       0.83      0.03      0.07       143
       short       0.62      0.11      0.18      1045
       sport       0.73      0.09      0.15        93
   talk-show       0.00      0.00      0.00        81
    thriller       0.23      0.01      0.02       309
         war       0.00      0.00      0.00        20
     western       0.97      0.58      0.73       200

    accuracy                           0.52     10843
   macro avg       0.41      0.14      0.16     10843
weighted avg       0.52      0.52      0.44     10843

In [15]:
sample_plot = ["A young boy discovers his magical powers and fights evil forces"]

sample_plot_clean = [clean_text(sample_plot[0])]
sample_plot_tfidf = tfidf.transform(sample_plot_clean)

predicted_genre = model.predict(sample_plot_tfidf)
print("Predicted Genre:", predicted_genre[0])

Predicted Genre: drama

In [16]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# ---------- LOAD DATA FUNCTION ----------
def load_data(file_path):
    data = []
    with open(file_path, "r", encoding="utf-8") as file:
        for line in file:
            data.append(line.strip().split(" ::: "))
    return data

# ---------- FILE PATHS ----------
train_path = "/kaggle/input/datasets/hijest/genre-classification-dataset-imdb/Genre Classification Dataset/train_data.txt"
test_path = "/kaggle/input/datasets/hijest/genre-classification-dataset-imdb/Genre Classification Dataset/test_data.txt"
solution_path = "/kaggle/input/datasets/hijest/genre-classification-dataset-imdb/Genre Classification Dataset/test_data_solution.txt"

# ---------- LOAD FILES ----------
train_df = pd.DataFrame(
    load_data(train_path),
    columns=["id", "title", "genre", "plot"]
)

test_df = pd.DataFrame(
    load_data(test_path),
    columns=["id", "title", "plot"]
)

test_solution_df = pd.DataFrame(
    load_data(solution_path),
    columns=["id", "title", "genre", "plot"]
)

# ---------- TEXT CLEANING ----------
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z]", " ", text)
    return text

train_df["plot"] = train_df["plot"].apply(clean_text)
test_df["plot"] = test_df["plot"].apply(clean_text)
test_solution_df["plot"] = test_solution_df["plot"].apply(clean_text)

# ---------- TRAINING ----------
X_train = train_df["plot"]
y_train = train_df["genre"]

tfidf = TfidfVectorizer(stop_words="english", max_features=5000)
X_train_tfidf = tfidf.fit_transform(X_train)

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

# ---------- TESTING ----------
X_test_tfidf = tfidf.transform(test_df["plot"])
test_df["predicted_genre"] = model.predict(X_test_tfidf)

# ---------- EVALUATION ----------
y_true = test_solution_df["genre"]
y_pred = test_df["predicted_genre"]

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))

Accuracy: 0.5233579335793358
              precision    recall  f1-score   support

      action       0.54      0.11      0.18      1314
       adult       0.51      0.06      0.11       590
   adventure       0.81      0.07      0.13       775
   animation       0.00      0.00      0.00       498
   biography       0.00      0.00      0.00       264
      comedy       0.51      0.42      0.46      7446
       crime       0.00      0.00      0.00       505
 documentary       0.57      0.87      0.69     13096
       drama       0.46      0.82      0.59     13612
      family       0.50      0.00      0.00       783
     fantasy       0.00      0.00      0.00       322
   game-show       0.98      0.32      0.48       193
     history       0.00      0.00      0.00       243
      horror       0.69      0.36      0.47      2204
       music       0.75      0.15      0.25       731
     musical       0.00      0.00      0.00       276
     mystery       0.00      0.00      0.00       318
        news       0.00      0.00      0.00       181
  reality-tv       0.58      0.02      0.05       883
     romance       0.00      0.00      0.00       672
      sci-fi       0.64      0.06      0.11       646
       short       0.59      0.12      0.20      5072
       sport       0.81      0.10      0.18       431
   talk-show       0.00      0.00      0.00       391
    thriller       0.30      0.02      0.03      1590
         war       0.00      0.00      0.00       132
     western       0.94      0.62      0.75      1032

    accuracy                           0.52     54200
   macro avg       0.38      0.15      0.17     54200
weighted avg       0.51      0.52      0.45     54200

In [17]:
print("Train Data:")
train_df

Train Data:

,id,title,genre,plot
0,1,Oscar et la dame rose (2009),drama,listening in to a conversation between his doc...
1,2,Cupid (1997),thriller,a brother and sister with a past incestuous re...
2,3,"Young, Wild and Wonderful (1980)",adult,as the bus empties the students for their fiel...
3,4,The Secret Sin (1915),drama,to help their unemployed father make ends meet...
4,5,The Unrecovered (2007),drama,the film s title refers not only to the un rec...
...,...,...,...,...
54209,54210,"""Bonino"" (1953)",comedy,this short lived nbc live sitcom centered on b...
54210,54211,Dead Girls Don't Cry (????),horror,the next generation of exploitation the siste...
54211,54212,Ronald Goedemondt: Ze bestaan echt (2008),documentary,ze bestaan echt is a stand up comedy about gr...
54212,54213,Make Your Own Bed (1944),comedy,walter and vivian live in the country and have...
54213,54214,Nature's Fury: Storm of the Century (2006),history,on labor day weekend the most intense h...

In [18]:
print("Test Data:")
test_df

Test Data:

,id,title,plot,predicted_genre
0,1,Edgar's Lunch (1998),l r brane loves his life his car his apart...,drama
1,2,La guerra de papá (1977),spain march quico is a very naughty chi...,drama
2,3,Off the Beaten Track (2010),one year in the life of albin and his family o...,documentary
3,4,Meu Amigo Hindu (2015),his father has died he hasn t spoken with his...,drama
4,5,Er nu zhai (1955),before he was known internationally as a marti...,drama
...,...,...,...,...
54195,54196,"""Tales of Light & Dark"" (2013)",covering multiple genres tales of light dar...,drama
54196,54197,Der letzte Mohikaner (1965),as alice and cora munro attempt to find their ...,drama
54197,54198,Oliver Twink (2007),a movie years in the making oliver twist ...,drama
54198,54199,Slipstream (1973),popular but mysterious rock d j mike mallard ...,drama
54199,54200,Curitiba Zero Grau (2010),curitiba is a city in movement with rhythms a...,documentary

In [19]:
print("\nTest Solution:")
test_solution_df

Test Solution:

,id,title,genre,plot
0,1,Edgar's Lunch (1998),thriller,l r brane loves his life his car his apart...
1,2,La guerra de papá (1977),comedy,spain march quico is a very naughty chi...
2,3,Off the Beaten Track (2010),documentary,one year in the life of albin and his family o...
3,4,Meu Amigo Hindu (2015),drama,his father has died he hasn t spoken with his...
4,5,Er nu zhai (1955),drama,before he was known internationally as a marti...
...,...,...,...,...
54195,54196,"""Tales of Light & Dark"" (2013)",horror,covering multiple genres tales of light dar...
54196,54197,Der letzte Mohikaner (1965),western,as alice and cora munro attempt to find their ...
54197,54198,Oliver Twink (2007),adult,a movie years in the making oliver twist ...
54198,54199,Slipstream (1973),drama,popular but mysterious rock d j mike mallard ...
54199,54200,Curitiba Zero Grau (2010),drama,curitiba is a city in movement with rhythms a...

In [20]:
# Training data shapes
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

# After TF-IDF (training)
print("X_train_tfidf shape:", X_train_tfidf.shape)

# Test data shape
print("X_test shape:", test_df["plot"].shape)

# After TF-IDF (testing)
print("X_test_tfidf shape:", X_test_tfidf.shape)

X_train shape: (54214,)
y_train shape: (54214,)
X_train_tfidf shape: (54214, 5000)
X_test shape: (54200,)
X_test_tfidf shape: (54200, 5000)

In [21]:
from sklearn.preprocessing import LabelEncoder

# Initialize label encoder
label_encoder = LabelEncoder()

# Encode training labels
y_train_encoded = label_encoder.fit_transform(y_train)

# Encode test solution labels (same encoder)
y_true_encoded = label_encoder.transform(test_solution_df["genre"])

# -------- PRINTING --------
print("Original Genres:")
print(label_encoder.classes_)

print("\nTotal number of classes:", len(label_encoder.classes_))

print("\nFirst 10 original labels:")
print(y_train[:10].values)

print("\nFirst 10 encoded labels:")
print(y_train_encoded[:10])

Original Genres:
['action' 'adult' 'adventure' 'animation' 'biography' 'comedy' 'crime'
 'documentary' 'drama' 'family' 'fantasy' 'game-show' 'history' 'horror'
 'music' 'musical' 'mystery' 'news' 'reality-tv' 'romance' 'sci-fi'
 'short' 'sport' 'talk-show' 'thriller' 'war' 'western']

Total number of classes: 27

First 10 original labels:
['drama' 'thriller' 'adult' 'drama' 'drama' 'documentary' 'comedy' 'crime'
 'reality-tv' 'horror']

First 10 encoded labels:
[ 8 24  1  8  8  7  5  6 18 13]

In [22]:
# Import Logistic Regression
from sklearn.linear_model import LogisticRegression

# -------- BUILD MODEL --------
# Logistic Regression with max iterations = 200
lr_model = LogisticRegression(max_iter=200, n_jobs=-1)

# -------- TRAIN MODEL --------
lr_model.fit(X_train_tfidf, y_train_encoded)

# -------- PREDICT ON TEST DATA --------
y_pred = lr_model.predict(X_test_tfidf)

# -------- INVERSE TRANSFORM PREDICTIONS --------
predicted_genres = label_encoder.inverse_transform(y_pred)

# -------- ADD PREDICTIONS TO TEST DATAFRAME --------
test_df["Predicted_Genre"] = predicted_genres

# -------- DISPLAY RESULT --------
test_df[["title", "Predicted_Genre"]].head()

                         title Predicted_Genre
0         Edgar's Lunch (1998)           short
1     La guerra de papá (1977)           drama
2  Off the Beaten Track (2010)     documentary
3       Meu Amigo Hindu (2015)           drama
4            Er nu zhai (1955)           drama

In [23]:
# Importing modules for metrics calculation
from sklearn.metrics import accuracy_score, classification_report

# -------- ACTUAL & PREDICTED LABELS --------
y_true = test_solution_df["genre"]
y_pred = test_df["Predicted_Genre"]

# -------- ACCURACY --------
accuracy = accuracy_score(y_true, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# -------- CLASSIFICATION REPORT --------
print("\nClassification Report:\n")
print(classification_report(y_true, y_pred))

Accuracy: 0.5839

Classification Report:

              precision    recall  f1-score   support

      action       0.48      0.29      0.36      1314
       adult       0.60      0.24      0.34       590
   adventure       0.57      0.16      0.25       775
   animation       0.50      0.06      0.11       498
   biography       0.00      0.00      0.00       264
      comedy       0.53      0.58      0.55      7446
       crime       0.35      0.04      0.07       505
 documentary       0.67      0.85      0.75     13096
       drama       0.54      0.77      0.64     13612
      family       0.50      0.09      0.15       783
     fantasy       0.51      0.06      0.10       322
   game-show       0.92      0.50      0.65       193
     history       0.00      0.00      0.00       243
      horror       0.64      0.57      0.61      2204
       music       0.68      0.46      0.55       731
     musical       0.27      0.02      0.04       276
     mystery       0.38      0.02      0.03       318
        news       0.71      0.07      0.12       181
  reality-tv       0.51      0.18      0.27       883
     romance       0.39      0.03      0.06       672
      sci-fi       0.55      0.26      0.35       646
       short       0.47      0.34      0.40      5072
       sport       0.65      0.26      0.38       431
   talk-show       0.60      0.16      0.26       391
    thriller       0.38      0.14      0.20      1590
         war       1.00      0.02      0.04       132
     western       0.90      0.73      0.81      1032

    accuracy                           0.58     54200
   macro avg       0.53      0.26      0.30     54200
weighted avg       0.56      0.58      0.55     54200

In [24]:
# Importing Multinomial Naive Bayes
from sklearn.naive_bayes import MultinomialNB

# -------- BUILD NAIVE BAYES MODEL --------
nb_model = MultinomialNB()

# -------- TRAIN NAIVE BAYES MODEL --------
nb_model.fit(X_train_tfidf, y_train_encoded)

MultinomialNB()

In [25]:
# -------- PREDICT ON TEST DATA --------
y_pred_nb = nb_model.predict(X_test_tfidf)

# -------- INVERSE TRANSFORM PREDICTIONS --------
predicted_genres_nb = label_encoder.inverse_transform(y_pred_nb)

# -------- ADD PREDICTIONS TO TEST DATAFRAME --------
test_df["Predicted_Genre"] = predicted_genres_nb

# -------- MERGE WITH TEST SOLUTION DATAFRAME --------
# (merge on id and title)
merged_df = test_df.merge(
    test_solution_df[["id", "title", "genre"]],
    on=["id", "title"],
    how="left",
    suffixes=("_pred", "_actual")
)

# -------- DISPLAY RESULT --------
merged_df[["title", "Predicted_Genre", "genre"]].head()

                         title Predicted_Genre        genre
0         Edgar's Lunch (1998)           drama     thriller
1     La guerra de papá (1977)           drama       comedy
2  Off the Beaten Track (2010)     documentary  documentary
3       Meu Amigo Hindu (2015)           drama        drama
4            Er nu zhai (1955)           drama        drama

In [26]:
# Importing modules for evaluation metrics
from sklearn.metrics import accuracy_score, classification_report

# -------- ACTUAL & PREDICTED LABELS --------
y_true_nb = merged_df["genre"]
y_pred_nb = merged_df["Predicted_Genre"]

# -------- ACCURACY FOR NAIVE BAYES --------
accuracy_nb = accuracy_score(y_true_nb, y_pred_nb)
print(f"Naive Bayes Accuracy: {accuracy_nb:.4f}")

# -------- CLASSIFICATION REPORT FOR NAIVE BAYES --------
print("\nNaive Bayes Classification Report:\n")
print(classification_report(y_true_nb, y_pred_nb))

Naive Bayes Accuracy: 0.5234

Naive Bayes Classification Report:

              precision    recall  f1-score   support

      action       0.54      0.11      0.18      1314
       adult       0.51      0.06      0.11       590
   adventure       0.81      0.07      0.13       775
   animation       0.00      0.00      0.00       498
   biography       0.00      0.00      0.00       264
      comedy       0.51      0.42      0.46      7446
       crime       0.00      0.00      0.00       505
 documentary       0.57      0.87      0.69     13096
       drama       0.46      0.82      0.59     13612
      family       0.50      0.00      0.00       783
     fantasy       0.00      0.00      0.00       322
   game-show       0.98      0.32      0.48       193
     history       0.00      0.00      0.00       243
      horror       0.69      0.36      0.47      2204
       music       0.75      0.15      0.25       731
     musical       0.00      0.00      0.00       276
     mystery       0.00      0.00      0.00       318
        news       0.00      0.00      0.00       181
  reality-tv       0.58      0.02      0.05       883
     romance       0.00      0.00      0.00       672
      sci-fi       0.64      0.06      0.11       646
       short       0.59      0.12      0.20      5072
       sport       0.81      0.10      0.18       431
   talk-show       0.00      0.00      0.00       391
    thriller       0.30      0.02      0.03      1590
         war       0.00      0.00      0.00       132
     western       0.94      0.62      0.75      1032

    accuracy                           0.52     54200
   macro avg       0.38      0.15      0.17     54200
weighted avg       0.51      0.52      0.45     54200

In [27]:
# Importing Support Vector Machine (SVM)
from sklearn.svm import LinearSVC

# -------- BUILD SVM MODEL (LINEAR KERNEL) --------
svm_model = LinearSVC()

# -------- TRAIN SVM MODEL --------
svm_model.fit(X_train_tfidf, y_train_encoded)

LinearSVC()

In [28]:
# -------- PREDICT ON TEST DATA --------
y_pred_svm = svm_model.predict(X_test_tfidf)

# -------- INVERSE TRANSFORM PREDICTIONS --------
predicted_genres_svm = label_encoder.inverse_transform(y_pred_svm)

# -------- ADD PREDICTIONS TO TEST DATAFRAME --------
test_df["Predicted_Genre"] = predicted_genres_svm

# -------- EVALUATE THE MODEL --------
from sklearn.metrics import accuracy_score, classification_report

y_true_svm = test_solution_df["genre"]
y_pred_svm_labels = test_df["Predicted_Genre"]

print(f"SVM Accuracy: {accuracy_score(y_true_svm, y_pred_svm_labels):.4f}")

print("\nSVM Classification Report:\n")
print(classification_report(y_true_svm, y_pred_svm_labels))

SVM Accuracy: 0.5719

SVM Classification Report:

              precision    recall  f1-score   support

      action       0.39      0.31      0.35      1314
       adult       0.51      0.36      0.43       590
   adventure       0.39      0.21      0.27       775
   animation       0.33      0.16      0.21       498
   biography       0.00      0.00      0.00       264
      comedy       0.53      0.56      0.54      7446
       crime       0.18      0.06      0.09       505
 documentary       0.69      0.82      0.75     13096
       drama       0.56      0.71      0.63     13612
      family       0.31      0.14      0.19       783
     fantasy       0.27      0.11      0.15       322
   game-show       0.77      0.61      0.68       193
     history       0.17      0.02      0.04       243
      horror       0.59      0.60      0.59      2204
       music       0.59      0.49      0.53       731
     musical       0.23      0.07      0.10       276
     mystery       0.19      0.05      0.08       318
        news       0.37      0.10      0.16       181
  reality-tv       0.40      0.26      0.31       883
     romance       0.22      0.06      0.09       672
      sci-fi       0.46      0.33      0.38       646
       short       0.43      0.33      0.38      5072
       sport       0.49      0.37      0.42       431
   talk-show       0.51      0.26      0.35       391
    thriller       0.30      0.16      0.21      1590
         war       0.38      0.12      0.18       132
     western       0.82      0.82      0.82      1032

    accuracy                           0.57     54200
   macro avg       0.41      0.30      0.33     54200
weighted avg       0.54      0.57      0.55     54200

In [29]:
# Importing modules for evaluation metrics
from sklearn.metrics import accuracy_score, classification_report

# -------- ACTUAL & PREDICTED LABELS --------
y_true_svm = test_solution_df["genre"]
y_pred_svm = test_df["Predicted_Genre"]

# -------- ACCURACY FOR SVM MODEL --------
accuracy_svm = accuracy_score(y_true_svm, y_pred_svm)
print(f"SVM Accuracy: {accuracy_svm:.4f}")

# -------- CLASSIFICATION REPORT FOR SVM MODEL --------
print("\nSVM Classification Report:\n")
print(classification_report(y_true_svm, y_pred_svm))

SVM Accuracy: 0.5719

SVM Classification Report:

              precision    recall  f1-score   support

      action       0.39      0.31      0.35      1314
       adult       0.51      0.36      0.43       590
   adventure       0.39      0.21      0.27       775
   animation       0.33      0.16      0.21       498
   biography       0.00      0.00      0.00       264
      comedy       0.53      0.56      0.54      7446
       crime       0.18      0.06      0.09       505
 documentary       0.69      0.82      0.75     13096
       drama       0.56      0.71      0.63     13612
      family       0.31      0.14      0.19       783
     fantasy       0.27      0.11      0.15       322
   game-show       0.77      0.61      0.68       193
     history       0.17      0.02      0.04       243
      horror       0.59      0.60      0.59      2204
       music       0.59      0.49      0.53       731
     musical       0.23      0.07      0.10       276
     mystery       0.19      0.05      0.08       318
        news       0.37      0.10      0.16       181
  reality-tv       0.40      0.26      0.31       883
     romance       0.22      0.06      0.09       672
      sci-fi       0.46      0.33      0.38       646
       short       0.43      0.33      0.38      5072
       sport       0.49      0.37      0.42       431
   talk-show       0.51      0.26      0.35       391
    thriller       0.30      0.16      0.21      1590
         war       0.38      0.12      0.18       132
     western       0.82      0.82      0.82      1032

    accuracy                           0.57     54200
   macro avg       0.41      0.30      0.33     54200
weighted avg       0.54      0.57      0.55     54200

In [30]:
# -------------------------------------------------
# Assuming lr_model, nb_model, svm_model are trained
# Assuming tfidf is the fitted TF-IDF vectorizer
# Assuming label_encoder is already fitted
# -------------------------------------------------

# New unseen movie descriptions
zoner_Description = [
    "Explosive fight scenes in the city streets",
    "A haunted mansion that traps its visitors",
    "A brave adventurer in search of lost treasure",
    "A forbidden romance in the 1920s",
    "A daring rescue mission with a love interest"
]

# -------- STEP 1: VECTORIZE NEW DATA --------
test_data_tfidf = tfidf.transform(zoner_Description)

# -------- STEP 2: PREDICTIONS --------

# Logistic Regression
y_pred_lr = lr_model.predict(test_data_tfidf)
predicted_genres_lr = label_encoder.inverse_transform(y_pred_lr)

# Naive Bayes
y_pred_nb = nb_model.predict(test_data_tfidf)
predicted_genres_nb = label_encoder.inverse_transform(y_pred_nb)

# SVM
y_pred_svm = svm_model.predict(test_data_tfidf)
predicted_genres_svm = label_encoder.inverse_transform(y_pred_svm)

# -------- STEP 3: OUTPUT RESULTS --------
print("Predicted Genres using Logistic Regression:")
print(predicted_genres_lr)
print()

print("Predicted Genres using Naive Bayes:")
print(predicted_genres_nb)
print()

print("Predicted Genres using SVM:")
print(predicted_genres_svm)
print("\n" + "="*100)

# -------- DETAILED OUTPUT --------
for i, message in enumerate(zoner_Description):
    print(f"Story : {message}")
    print(f"\tNaive Bayes Prediction        : {predicted_genres_nb[i]}")
    print(f"\tLogistic Regression Prediction: {predicted_genres_lr[i]}")
    print(f"\tSVM Prediction                : {predicted_genres_svm[i]}")
    print("="*100)

Predicted Genres using Logistic Regression:
['documentary' 'horror' 'adventure' 'drama' 'action']

Predicted Genres using Naive Bayes:
['documentary' 'horror' 'documentary' 'drama' 'drama']

Predicted Genres using SVM:
['documentary' 'comedy' 'family' 'drama' 'adventure']

====================================================================================================
Story : Explosive fight scenes in the city streets
	Naive Bayes Prediction        : documentary
	Logistic Regression Prediction: documentary
	SVM Prediction                : documentary
====================================================================================================
Story : A haunted mansion that traps its visitors
	Naive Bayes Prediction        : horror
	Logistic Regression Prediction: horror
	SVM Prediction                : comedy
====================================================================================================
Story : A brave adventurer in search of lost treasure
	Naive Bayes Prediction        : documentary
	Logistic Regression Prediction: adventure
	SVM Prediction                : family
====================================================================================================
Story : A forbidden romance in the 1920s
	Naive Bayes Prediction        : drama
	Logistic Regression Prediction: drama
	SVM Prediction                : drama
====================================================================================================
Story : A daring rescue mission with a love interest
	Naive Bayes Prediction        : drama
	Logistic Regression Prediction: action
	SVM Prediction                : adventure
====================================================================================================